// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.
$(function () {
	$(".ny_zblb1 ul li").click(function(){
		var thisSpan=$(this);
		$(".ny_zblb1 ul li ul").prev("a").removeClass("cur");
		$("ul", this).prev("a").addClass("cur");
		$(this).children("ul").slideDown("fast");
		$(this).siblings().children("ul").slideUp("fast");
	})
});

  $(function(){
	  $('.carousel').carousel({
		  interval: 4000
	  })
	  $("#myCarousel").carousel('cycle');
	  
   });
 